server:
  port: 8092

spring:
  application:
    name: redis-example

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    vectorstore:
      redis:
        initialize-schema: true
        prefix: yingzi_prefix_spring_ai
        index: yingzi_index_spring_ai

  data:
    redis:
      host: localhost
      port: 6379 # Redis服务器连接端口