server:
  port: 8085

spring:
  application:
    name: mcp-server-webflux
  main:
    banner-mode: off
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    mcp:
      server:
        name: weather-time-translate
        version: 0.0.1

    toolcalling:
      baidutranslate:
        app-id: ${BAIDU_TRANSLATE_APP_ID}
        secret-key: ${BAIDU_TRANSLATE_SECRET_KEY}
# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG