server:
  port: 8091

spring:
  application:
    name: vector-elasticsearch-example

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: yingzi_spring_ai
        similarity: cosine
        dimensions: 1536

  elasticsearch:
    uris: https://127.0.0.1:9200
    username: elastic
    password: yingzi
