server:
  port: 8090

spring:
  application:
    name: Elasticsearch-example

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    vectorstore:
      elasticsearch:
        index-name: yingzi_spring_ai
        similarity: cosine
        dimensions: 1536

  elasticsearch:
    uris: https://127.0.0.1:9200
    username: elastic
    password: yingzi
